### ISSUE TITLE
childrenKey 能否支持函数类型，让用户根据节点来判断 children 的字段名

### ISSUE THREAD

**Issue by tangdw** [zhangshichun/tree-lodash#12]
如题 `childrenKey: (node: any) => string`

**Comment by zhangshichun** [comment]
> 如题 `childrenKey: (node: any) => string`

感觉可以安排一下..

**Comment by zhangshichun** [comment]
> 如题 `childrenKey: (node: any) => string`

在v0.2.0中已经支持了动态childrenKey的能力：
https://zhangshichun.github.io/tree-lodash/guide/features.html#%E4%B8%89%E3%80%81options-getchildrenkey-%E6%94%AF%E6%8C%81%E4%B8%80%E6%A3%B5%E6%A0%91%E4%B8%8A%E5%A4%9A%E7%A7%8D-childrenkey
