### ISSUE TITLE
调用map，返回新的树节点异常，缺少字段

### ISSUE THREAD

**Issue by allen2001** [zhangshichun/tree-lodash#20]
```
const formatTree = window.treeLodash.map(treeData, (node, meta) => {
    return {
      id: node.dicId,
      name: node.name,
      code: node.code,
      pcode: node.pcode,
      dicCode: node.dicCode,
      depth: meta.depth,
      children: node.list,
    };
  }, {
    childrenKey: 'list'
  });
```
使用类似结构调用map方法，返回的新的树节点对象会同时包含list和children两个key，list中的子节点返回正常，但是children中的子节点缺少children字段 **（children: node.list 未生效）**

**Comment by zhangshichun** [comment]
目前 `map` 方法的职能很单一：把回调中 `return` 的对象浅克隆成一个新对象，并通过 `childrenKey` 组装新的子节点，组成一颗新树。
你的期望是 children可以指向新生成的对象，这对当前的 `map` 方法来说并不适用(你赋给node的chilren是老的list引用，并不是新生成的list)。

我推荐你这样实现：
```js
const formatTree = window.treeLodash.map(treeData, (node, meta) => {
    return {
      id: node.dicId,
      name: node.name,
      code: node.code,
      pcode: node.pcode,
      dicCode: node.dicCode,
      depth: meta.depth,
    };
  }, {
    childrenKey: 'list'
  });
window.treeLodash.foreach(formatTree, (node) =>{ node.children = node.list}, { childrenkey: 'list' })
```

**Comment by zhangshichun** [comment]
> ```
> const formatTree = window.treeLodash.map(treeData, (node, meta) => {
>     return {
>       id: node.dicId,
>       name: node.name,
>       code: node.code,
>       pcode: node.pcode,
>       dicCode: node.dicCode,
>       depth: meta.depth,
>       children: node.list,
>     };
>   }, {
>     childrenKey: 'list'
>   });
> ```
> 
> 使用类似结构调用map方法，返回的新的树节点对象会同时包含list和children两个key，list中的子节点返回正常，但是children中的子节点缺少children字段 **（children: node.list 未生效）**

试试上面的代码

**Comment by allen2001** [comment]
```
...
window.treeLodash.foreach(formatTree, (node) => {
  node.children = node.list;
  delete node.list; // 删除原始数据中的list字段
})
```
稍微改了下实现可以了，原本是想把后端接口中的list字段直接替换成children，就联想到Array.prototype.map这种方式去做替换，但是忽略了这里的treeData有层级，返回的新节点中貌似还必须保留原有的childrenKey字段
