### ISSUE TITLE
filter是不是有问题？

### ISSUE THREAD

**Issue by Gkood** [zhangshichun/tree-lodash#21]
第一级不符合，第二级有符合的，但是过滤不出来

**Comment by zhangshichun** [comment]
> 第一级不符合，第二级有符合的，但是过滤不出来

按这个预期的话，确实是有问题的；
如果只是过滤节点，这个写法肯定可行：
```js
toArray(data).filter(t => t.id > 100)
```

`tree-lodash`的filter 之前的更像是“对一棵现有的树进行裁剪”的意思，它会尽可能返回原有结构。
这个在使用上确实好像可能会引入误解，需要思考一下，是不是可以加个配置项，允许继续向下搜索

**Comment by zhangshichun** [comment]
![image](https://github.com/zhangshichun/tree-lodash/assets/15374687/eeb5cbc4-ced4-4047-8e59-ebf6b08fb47b)
以上图为例，如果按你的预期返回，那原本的一棵树结构，就会被拆成两个独立的树；而且原本叔侄关系的节点，会变成兄弟关系；这显然更会导致错误的认知；

因此在树上如何`filter`，显然是个需要深入思考的问题

**Comment by ali-pay** [comment]
你好，匹配到子级的节点的时候可以保留父级节点么？filter 只希望把不相关的兄弟节点剔除

**Comment by zhangshichun** [comment]
> 你好，匹配到子级的节点的时候可以保留父级节点么？filter 只希望把不相关的兄弟节点剔除

描述的还是稍微有点抽象兄弟。
再捋一下，你是不是希望遍历整颗树，把符合要求的节点，以及他们的祖先节点都保留下来，并形成一颗树？
