### ISSUE TITLE
请求增加功能

### ISSUE THREAD

**Issue by YjanuaryWay** [zhangshichun/tree-lodash#22]
我需要下面这3个功能：
export class Tree<TNode> {
  /**从当前元素开始（包含），向上冒泡，直到指定的祖先元素（不包含），每个元素都执行一次回调，如果回调返回true，则终止冒泡。*/
  static bubbleCall(node: any, callback: (node: any) => boolean, parent: any): any {
    if (node === parent || callback(node))
      return node;
    return Tree.bubbleCall(node.parentElement, callback, parent);
  };

  /**从当前元素开始（包含），向上冒泡，直到指定的祖先元素（不包含），找到第一个符合要求的元素,执行回调，并返回回调结果。*/
  static onClosest<TNode extends {parentElement:TNode}>(currentNode: TNode, predict: (node: TNode) => boolean, callback: (node: TNode) => TNode, parent: TNode): TNode | undefined {
    if (predict(currentNode))
      return callback(currentNode);
    if (currentNode !== parent && currentNode.parentElement)
      return Tree.onClosest(currentNode.parentElement, predict, callback, parent);
  };

  //static toArray(){
//
  //}

  /** array 组装成树 */
  static array2tree(array,idStr='id',parentStr='parent',rootStr=1){
    let group = {};
    array.forEach(node=>{
        let parent = group[node[parentStr]] = group[node[parentStr]] || [,[]];
        parent[1].push(node);
        let self = group[node[idStr]] = group[node[idStr]] || [,[]];
        node.children = self[1];
        self[0] = node;
    })
    return group[rootStr][0];
}
}
大佬能不能加到库中？

**Comment by zhangshichun** [comment]
一、/**从当前元素开始（包含），向上冒泡，直到指定的祖先元素（不包含），每个元素都执行一次回调，如果回调返回true，则终止冒泡。*/

这个现在其实有找到祖先元素的能力，
```
let parentsAndSelf
find(tree, (node, { parents }) => {
  const matched = node.id  === 'xxx'
  if (matched) {
    parentsAndSelf = [...parents, node]
  }
   return matched 
})
```
至于后续消费，你可以看情况来，这肯定不属于这个通用库；

**Comment by zhangshichun** [comment]
二、/**从当前元素开始（包含），向上冒泡，直到指定的祖先元素（不包含），找到第一个符合要求的元素,执行回调，并返回回调结果。*/

如上，拿到祖先列表了其实其他都好办了；

**Comment by zhangshichun** [comment]
三、same as https://github.com/zhangshichun/tree-lodash/issues/15

**Comment by zhangshichun** [comment]
`fromArray` is done:  https://zhangshichun.github.io/tree-lodash/functions/fromArray.html

**Comment by YjanuaryWay** [comment]
thanks for you！



---原始邮件---
发件人: "Brother ***@***.***&gt;
发送时间: 2024年5月6日(周一) 上午10:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhangshichun/tree-lodash] 请求增加功能 (Issue #22)




 
Closed #22 as completed.
