### ISSUE TITLE
fromArray可以增加一个排序字段吗

### ISSUE THREAD

**Issue by firmianaQ** [zhangshichun/tree-lodash#25]

**Comment by zhangshichun** [comment]
诉求是兄弟节点之间固定顺序吗？

**Comment by zhangshichun** [comment]
目前来看，只要你入参的 `array` 是固定顺序的，兄弟节点的顺序应该就是稳定的。
所以你其实可以先 `.sort()` 然后再 `.fromArray()`

**Comment by firmianaQ** [comment]
> 目前来看，只要你入参的 `array` 是固定顺序的，兄弟节点的顺序应该就是稳定的。 所以你其实可以先 `.sort()` 然后再 `.fromArray()`

我现在就是这么做的
